### ISSUE TITLE
header

### ISSUE THREAD

**Issue by AngeloC89** [AngeloC89/php-oop-2#1]
Spett.le Sig. Nicola Filannino [Nome dell'azienda o del referente]
Con la presente vorrei porgere i miei più cordiali saluti e manifestare il mio sincero apprezzamento per le sue eccellenti capacità nel campo del web design.

Come lei ben saprà, la prima impressione è fondamentale, soprattutto nel mondo digitale. Per questo motivo, desidero rivolgermi a lei con la speranza di poter collaborare alla creazione di un header per il nostro shop online che sia non solo accattivante e moderno, ma anche in grado di trasmettere i valori e l'identità del nostro marchio.

L'idea che abbiamo in mente è quella di un header minimalista e raffinato, con una navbar intuitiva e facile da navigare, che integri il nome del nostro shop in modo elegante e distintivo. Siamo convinti che lei saprà dar vita a una soluzione perfetta che rispecchi le nostre esigenze e che ci aiuti a distinguerci dalla concorrenza.

Confidiamo nella sua professionalità e nella sua creatività e restiamo a disposizione per fornirle ulteriori dettagli e chiarimenti su ciò che abbiamo in mente.

In attesa di un suo cortese riscontro, le porgiamo i nostri più distinti saluti.

Cordiali saluti,

**Comment by AngeloC89** [comment]
git fetch origin
git checkout 1-header

**Comment by Nik0-9** [comment]
navbar done
